### ISSUE TITLE
Documentation for web componenets

### ISSUE THREAD

**Issue by sta-szek** [zeroturnaround/bamboo-liverebel-plugin#2]
Hi, this is not related to plugin itself, I would rather get some information, where can I find documentation about web plugin development, especially tags like `[@ww....` -- I cannot find it anywhere on the internet.
I also created question in atlassian community, but I don't expect they will answer me :(
https://community.atlassian.com/t5/Bamboo-questions/Where-can-I-find-UI-plugin-documentation/qaq-p/833068

**Comment by toomasr** [comment]
Cannot help on this but this was a great reminder from you that we should shut this project down as the LiveRebel product has been discontinued 4+ years and 3+ years since end of life.
